### ISSUE TITLE
Understand requirements for Matlab - proseco interface regarding monitor windows

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#72]
Overall, the interaction needs to be discussed with FOT MP to ensure that their process and Matlab code will play nicely with our concept of a single call to `get_aca_catalog` with `n_guide=4` (e.g.).

One extreme corner case is where a monitor window is required and it is a chosen guide star but should *NOT* be converted.  Not clear if this would ever happen (so not necessarily a requirement for 4.0).

**Comment by jeanconn** [comment]
I've been thinking about this a bit more and looking over the code.  I think we could still go either way, with those ways being:

1) proseco is more involved in the process and "helps out" by determining the DTS and seeing if the MON coordinates overlap with a guide star and converting to guide via built-in rules if necessary.  The OR pieces that define the monitor window would need to end up in the StarSelector and the proseco returns about the monitor window would need to be assigned back into the selected ACACatalog.  Much testing would need to be done with regard to the "gotchas" already in the code (specially preserving or not any edits to the MON)

2) proseco doesn't do anything with monitor windows and they work as before

The problem you mentioned with 2 is that we'd probably want the rule for "convert MON to GUI" to be based on information not presently passed back to SAUSAGE (selected as a guide star at later stage or?) and would be difficult for mission planners to apply.

I still think 2) might be the way to go.  It would be a trivial change to actually pass some more stage information from the current guide star selection to SAUSAGE to help inform the "maybe convert to GUI" choice (if we can decide on something like that... but I'm not totally convince).  Otherwise, I think this convert to gui question might deserve ACA pre-review input (and run an annie SIM with the star).

Regarding scale, there are 5 remaining cycle 19 mon windows (basically already scheduled through the end of the year) and 14 cycle 20 windows

**Comment by jeanconn** [comment]
Right now the plan is to do nothing on either the MATLAB or proseco sides but to plan sit down and review all monitor process with the FOT, then document and review when making test plan.
