### ISSUE TITLE
No fids found for obsid 20259

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#88]
Was using AUG2018B for testing and it looks like this obsid doesn't end up with any fids.  While a useful test for confirming the error handling this should probably work.  Hopefully fixed by #59 

```
  0.001 get_fid_candidates  : Initial candidate fid ids are [1, 2, 3, 4]
  0.013 set_spoilers_score  :     Set fid 2 spoiler score to 1
  0.022 set_spoilers_score  :     Set fid 4 spoiler score to 4
  0.023 set_initial_catalog : No acceptable fid sets (off-CCD or spoiled by field stars)
```

**Comment by taldcroft** [comment]
Fid selection is not complete and this lack of selected fids is expected.  Validation testing (on hundreds / thousands of obsids) will pick up any issues like this.

Keeping this open for now because the flight starcheck review showed no fid spoiler for id=2.  Presumably proseco is using a wider spatial filter, or else there is a bug.

**Comment by jeanconn** [comment]
Indeed.  I had also noticed in passing this was HRC-S and figured it would be a useful dev/test case.
